name: Run ETL Pipeline

on:
  schedule:
    - cron: '0 0 */7 * *'  # Every week
  workflow_dispatch:       # Manual trigger support

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/data_pipeline/requirements_pipeline.txt

      - name: Run ETL script
        env:
          MONGO_PWD: ${{ secrets.MONGO_PWD }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          CLUSTER: ${{ secrets.CLUSTER }}
          PYTHONPATH: backend
        run: |
          python -u backend/data_pipeline/run_pipeline.py
