name: Run ETL Pipeline

on:
  schedule:
    - cron: '0 0 */7 * *'  # Every week
  workflow_dispatch:       # Manual trigger support

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -qqy
          sudo apt-get -qqy install google-chrome-stable
          google-chrome --version

      - name: Install Chrome WebDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F. '{print $1}')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/data_pipeline/requirements_pipeline.txt
          pip install webdriver-manager  # Additional dependency for better webdriver management

      - name: Run ETL script
        env:
          MONGO_PWD: ${{ secrets.MONGO_PWD }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          CLUSTER: ${{ secrets.CLUSTER }}
          PYTHONPATH: backend
          GITHUB_ACTIONS: true
        run: |
          python -u backend/data_pipeline/run_pipeline.py